// Generated by CoffeeScript 1.9.1
(function () {
  var xml2js;

  xml2js = require('./xml2js');

  exports.stripBOM = function (str) {
    if (str[0] === '﻿') {
      return str.substring(1);
    } else {
      return str;
    }
  };
}).call(this);